spring:
  profiles:
    active: dev # during production this value will be replaced with "prod" from deployment environment variable
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api
server:
  port: 80
