spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    url: ${datasource-url} # secret from Azure Key Vault
    username: ${datasource-username} # secret from Azure Key Vault
    password: ${datasource-password} # secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none #Turn off DDL autogeneration
