spring:
  profiles:
    active: dev # during production this value will be replaced with "prod" from deployment environment variable
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - env
          - beans
          - configprops
          - heapdump
          - httpexchanges
          - loggers
          - mappings
          - prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values:  always
    configprops:
      show-values:  always
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled:  true
    os:
      enabled:  true
  tracing:
    sampling:
      probability:  1 # Only for demo purpose
info:
  app:
    name: sika-backend
    description: SIKA backend service
    version: @project.version@
    author: Agrowculture
    links:
      github: https://github.com/agrowculture/sika-backend
