spring:
  datasource:
    url: jdbc:h2:mem:sika
    username: admin
    password:
  jpa:
    show-sql: true
  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
